### ISSUE TITLE
A salesperson can fully define a service contract in Odoo

### ISSUE THREAD

**Issue by mdurepos** [Bemade/bemade-addons#41]
The thinking is to use blanket orders to build out sale orders.
Think about: 
* How SOs are built relative to visits
* How tasks are assigned
* How multiple equipments are handled
* How different types of visits are handled

Maybe take Lakeshore as the easy to manage example, the CHUM contract for PM as hell mode and the Epocal SO as examples

# Requirements Analysis

## Single Equipment SO

One equipment serviced. All tasks produced refer to the equipment on the SO or the equipment defined by their task templates.

## Multi-Equipment SO

Recommendation is to use one SO line per intervention (task - equipment pair). Equipment is set per SO line. Setting globally on the SO sets all lines to the selected equipment (they can be set individually thereafter).

For batching interventions (i.e. multiple tasks for the same piece of equipment on a single SO line), use a task template with hierarchy.

## Service Contract

Given the above structures, a service contract is a sales blanket order that mirrors the equipment - sale order line structure from SOs.

# User Stories

## Setting up a service contract for semi-annual SIPs on a single client system

**TODO: Figure out how to document visit frequency on the blanket**

 1. The salesperson creates a Blanket Sales Order, selecting the correct client and shipping address.
 2. The salesperson defines the equipment present at the shipping address, along with any site-specific contact information.
 3. The salesperson makes sure to set the equipment field on the Blanket SO.
 4. The salesperson enters the correct standard service products with the correct quantities for two visits (in this case, FEE-SIP with a quantity of 2).
 5. Once the contract is accepted by the client (a PO is received), the service coordinator validates the blanket.
 6. The service coordinator creates sales orders from the blanket (one for each visit), and confirms these after having set the promised dates. Alternately, he can set activities on the Blanket as reminders to create sales orders, if he prefers.
 7. The service tasks are managed as per usual.

## Setting up a service contract for monthly visits on multiple systems at the same location

**TODO: Think about implementing auto-creation of the sections when a new piece of equipment is selected for a line**

 1. The salesperson creates a Blanket Sales Order, selecting the correct client and shipping address.
 2. The salesperson enters the standard service products with one line per equipment serviced, and selects the corresponding equipment. For example, 3 lines with 2 FEE-CIP RO-4 for executing 6 total CIPs semi-annually on 3 different systems. The SO should be broken down with sections either by visit schedule (one section per visit) or by equipment (one section per equipment).
 3. Follow steps 5-7 above for the approval process.

**Comment by itdurpro** [comment]
# Features to develop:

- [ ] It should be possible to indicate that a service SO line is linked to zero or more equipments.
- [ ] It should be possible for a task to be linked to zero or more equipments.
- [ ] Blanket SOs should have an equipment field, just like SOs.
- [ ] Setting the equipment field on blanket SOs and on SOs should re-set all the SO lines to target that equipment.
- [ ] The equipment covered by a blanket SO and an SO should be summarized on the form view.
- [ ] The equipment covered by a blanket SO and an SO should be summarized on the PDFs.
- [ ] There should be a mapping between estimated visit date and SO lines + quantity to deliver during those visits.
